;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        coffee-dedent-line-backspace
        comment-dwim
        crux-move-beginning-of-line
        dired-toggle-read-only
        downcase-region
        enh-ruby-electric-brace
        go-mode-insert-and-indent
        kill-buffer
        mark-word
        org-delete-char
        ruby-electric-curlies
        ruby-electric-space
        sh-assignment
        swiper
        upcase-region
        upcase-region
        wdired-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        ace-window
        backward-sentence
        beginning-of-buffer
        counsel-find-file
        end-of-buffer
        eval-print-last-sexp
        flymake-goto-next-error
        go-goto-imports
        graphviz-dot-preview
        ido-switch-buffer
        ivy-switch-buffer
        kill-region
        magit-status
        markdown-exdent-or-delete
        mouse-set-region
        org-self-insert-command
        ruby-electric-matching-char
        shell-command-on-region
        ))
