;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-lt-gt
        coffee-dedent-line-backspace
        upcase-region
        downcase-region
        enh-ruby-electric-brace
        go-mode-insert-and-indent
        kill-buffer
        mark-word
        org-delete-char
        ruby-electric-curlies
        ruby-electric-space
        upcase-region
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        counsel-find-file
        end-of-buffer
        ido-switch-buffer
        kill-region
        magit-status
        markdown-exdent-or-delete
        org-self-insert-command
        ruby-electric-matching-char
        ))
